### ISSUE TITLE
xcode 6 support

### ISSUE THREAD

**Issue by dekeract** [substantial/choosy#14]
Hi! 
ChoosyAppTypeParameter class has property "description" which in new xcode 6 conflicts with NSObject property "description".  

Here is a warning text: "Auto property synthesis will not synthesize property 'description' because it is 'readwrite' but it will be synthesized 'readonly' via another property"

That's why app crashes when calls method ]Choosy registerAppTypes]

Here is an exeption: "Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ChoosyAppTypeParameter 0x7fad950180b0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key description."

Can you please fix it? It would be very good. 

Thanks.

**Comment by eagsalazar** [comment]
Hi dekeract, can you provide a pull request?

Thanks!

**Comment by dekeract** [comment]
I provide a pull request. Sorry for big delay with it.
