### ISSUE TITLE
Split demo app off into a separate repo

### ISSUE THREAD

**Issue by gamenerds** [substantial/choosy#7]

**Comment by squarefrog** [comment]
I disagree with this. As it stands currently you are able to quickly try out choosy by running `pod try choosy` in the terminal. If the demo app is split then this functionality disappears.

It's fairly common practice to include the demo in the source repo. If you include the framework with Cocoapods then only the source code is used so theres no real benefit to splitting.

**Comment by gamenerds** [comment]
Thanks, @squarefrog! And you're right - I did change this repo and added Podfile to keep everything in one place yesterday, but forgot to close this issue. Still new to CocoaPods so had the silly idea that separation was necessary.better. :)

**Comment by squarefrog** [comment]
No problem! I <3 CocoaPods so if theres any advice I can give feel free to shoot me a message.

**Comment by gamenerds** [comment]
Thank you, Paul! Noted :)
